export const LOAD_ALL_TASKS_ERROR = 'LOAD_ALL_TASKS_ERROR';
export const LOAD_ALL_TASKS = 'LOAD_ALL_TASKS';
export const LOAD_ALL_TASKS_SUCCESS = 'LOAD_ALL_TASKS_SUCCESS';

export const LOAD_ACTIVE_TASKS_ERROR = 'LOAD_ACTIVE_TASKS_ERROR';
export const LOAD_ACTIVE_TASKS = 'LOAD_ACTIVE_TASKS';
export const LOAD_ACTIVE_TASKS_SUCCESS = 'LOAD_ACTIVE_TASKS_SUCCESS';

export const LOAD_CURRENT_TASK_ERROR = 'LOAD_CURRENT_TASK_ERROR';
export const LOAD_CURRENT_TASK = 'LOAD_CURRENT_TASK';
export const LOAD_CURRENT_TASK_SUCCESS = 'LOAD_CURRENT_TASK_SUCCESS';

export const EDIT_CURRENT_TASK_ERROR = 'EDIT_CURRENT_TASK_ERROR';
export const EDIT_CURRENT_TASK = 'EDIT_CURRENT_TASK';
export const EDIT_CURRENT_TASK_SUCCESS = 'EDIT_CURRENT_TASK_SUCCESS';